---
- name: Copy Kubeconfig for LB01
  hosts: all
  become: yes
  vars:
    ansible_user:                 "{{ lookup('env', 'ANSIBLE_USER') }}"
  tasks:
    - name: Ensure .kube directory exists
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Check if kubeconfig file exists
      stat:
        path: /root/install_dir/auth/kubeconfig
      register: kubeconfig_stat

    - name: Debug kubeconfig file status
      debug:
        var: kubeconfig_stat

    - name: Copy kubeconfig to ansible_user's home directory
      copy:
        src: /root/install_dir/auth/kubeconfig
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      when: kubeconfig_stat.stat.exists

    - name: Set KUBECONFIG environment variable for ansible_user
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
        create: yes

    - name: Set KUBECONFIG environment variable for root
      lineinfile:
        path: /root/.bashrc
        line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
        create: yes
        
    - name: Ensure CSR approval script is present
      copy:
        dest: /usr/local/bin/approve-csrs.sh
        content: |
          #!/bin/bash
          export HOME=/home/{{ ansible_user }}
          export KUBECONFIG=$HOME/.kube/config

          # Log environment to file for debugging
          echo "Running approve-csrs.sh" >> /var/log/approve-csrs.log
          echo "HOME=$HOME" >> /var/log/approve-csrs.log
          echo "KUBECONFIG=$KUBECONFIG" >> /var/log/approve-csrs.log
          echo "PATH=$PATH" >> /var/log/approve-csrs.log

          /usr/local/bin/oc get csr -o go-template='{% raw %}{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}{% endraw %}' | xargs /usr/local/bin/oc adm certificate approve
 
    - name: Enable approve-csrs script
      command: chmod +x /usr/local/bin/approve-csrs.sh
